apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver-proxy
  namespace: kube-system
  labels:
    component: kube-apiserver-proxy
spec:
  priorityClassName: system-cluster-critical
  containers:
  - name: kube-apiserver-proxy
    image: nginx:1.19.1-alpine
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: apiserver-proxy-conf
      readOnly: true
  hostNetwork: true
  volumes:
  - name: apiserver-proxy-conf
    hostPath:
      path: /etc/kubernetes/apiserver-proxy.conf
      type: File
