kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
  namespace: kube-addons
  labels:
    app: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: kube-addons
